### PR TITLE
Fix Guardian reboot when time set from 2015 to 2022

### LINKED ISSUE #171: Guardian not reboot when time changed
Issue: Guardian now will reboot if system time change - the current case is time changed from Swarm
DoD: Guardian won't reboot if system time change

### PR DESCRIPTION
**Pull request by Tooseriuz**
Resolve #171 
- Add prefs for `enable_schedule_reboot`

### CODE REVIEW

File: lib-core/src/main/java/org/rfcx/guardian/utility/rfcx/RfcxPrefs.java [hunk 1]
```diff
@@ -145,8 +145,9 @@
                 put(Pref.ADMIN_WIFI_CLIENT_AUTH_CREDS, "[ssid]:[password]");
                 put(Pref.ADMIN_WIFI_HOTSPOT_AUTH_CREDS, "[ssid]:rfcxrfcx");
                 put(Pref.ADMIN_BLUETOOTH_FUNCTION, "off");
-
                 put(Pref.ENABLE_FILE_SOCKET, "false");
+
+                put(Pref.ENABLE_SCHEDULE_REBOOT, "false");
```
Comment (antonyharfield) [inline lib-core/src/main/java/org/rfcx/guardian/utility/rfcx/RfcxPrefs.java]: _Proximity to related code_ is a way to make code easier to read/find.
=> This should be above the pref `REBOOT_FORCED_DAILY_AT`.

_Related code follows same naming_.
=> If you put it together then you would have also noticed that the name is "forced" instead of "scheduled". Suggest new pref is `ENABLE_REBOOT_FORCED_DAILY`.

File: lib-core/src/main/java/org/rfcx/guardian/utility/rfcx/RfcxPrefs.java [hunk 2]
```diff
@@ -648,6 +649,8 @@ public JSONObject getPrefsAsJsonObj(String[] includeTheseKeys) {
         public static final String API_SATELLITE_PROTOCOL = "api_satellite_protocol";
 
         public static final String ENABLE_FILE_SOCKET = "enable_file_socket";
+
+        public static final String ENABLE_SCHEDULE_REBOOT = "enable_schedule_reboot";
```
Comment (antonyharfield) [inline lib-core/src/main/java/org/rfcx/guardian/utility/rfcx/RfcxPrefs.java]: Same...
1. Proximity
2. Naming

File: role-guardian/src/main/res/xml/prefs.xml [hunk 3]
```diff
@@ -697,5 +697,14 @@
...
 
+    <ListPreference
+            android:defaultValue="@string/prefs_value_default_enable_schedule_reboot"
+            android:dialogTitle="enable_schedule_reboot"
+            android:entries="@array/prefs_values_true_or_false"
+            android:entryValues="@array/prefs_values_true_or_false"
+            android:key="enable_schedule_reboot"
+            android:summary="string - true/false"
+            android:title="enable_schedule_reboot" />
+
```
Comment (antonyharfield) [inline role-guardian/src/main/res/xml/prefs.xml]: Same.

**Review by antonyharfield — CHANGES_REQUESTED** [review]

**Review by antonyharfield — APPROVED** [review]
