### PR TITLE
Fix same detection in every segment payload

### LINKED ISSUE #173: Fix Swarm Guardian send same detection in every message
Issue: Swarm guardian now send same detection over every messages
DoD: not send same detection on every messages

### PR DESCRIPTION
**Pull request by Tooseriuz**
Resolve #173 
- for swarm Guardian, it will get only detection that not accessed yet
- for swarm Guardian, it will delete detections row not update accessed timestamp

### CODE REVIEW

File: role-guardian/src/main/java/org/rfcx/guardian/guardian/api/methods/ping/ApiPingJsonUtils.java [hunk 1]
```diff
@@ -129,8 +129,13 @@ public String buildPingJson(boolean includeAllExtraFields, String[] includeExtra
         }
 
         if ((includeAllExtraFields && (includeAssetBundleCount > 0)) || ArrayUtils.doesStringArrayContainString(includeExtraFields, "detections")) {
-            jsonObj = app.audioDetectionJsonUtils.retrieveAndBundleDetectionJson(jsonObj, Math.max(includeAssetBundleCount, 1), false);
-            includePurgedAssetList = true;
+            if (app.rfcxPrefs.getPrefAsString(RfcxPrefs.Pref.API_SATELLITE_PROTOCOL).equalsIgnoreCase("swm")) {
```
Comment (antonyharfield) [inline role-guardian/src/main/java/org/rfcx/guardian/guardian/api/methods/ping/ApiPingJsonUtils.java]: It's possible that a Cell Guardian can have API_SATELLITE_PROTOCOL set, so is this correct? The only way to be sure that it is a Satellite Guardian is to check the protocol order for "sat".

File: role-guardian/src/main/java/org/rfcx/guardian/guardian/asset/detections/AudioDetectionJsonUtils.java [hunk 2]
```diff
@@ -42,7 +46,11 @@ public JSONObject retrieveAndBundleDetectionJson(JSONObject insertDetectionsInto
             dtcnList.add(TextUtils.join("*", new String[]{dtcnRow[1], dtcnRow[3] + "-v" + dtcnRow[4], dtcnRow[7], "" + Math.round(Double.parseDouble(dtcnRow[8]) * 1000), dtcnRow[10]}));
 
             // mark this row as accessed in the database
-            app.audioDetectionDb.dbFiltered.updateLastAccessedAtByCreatedAt(dtcnRow[0]);
+            if (forSatellite) {
+                app.audioDetectionDb.dbFiltered.deleteSingleRow(dtcnRow[1], dtcnRow[6]);
+            } else {
+                app.audioDetectionDb.dbFiltered.updateLastAccessedAtByCreatedAt(dtcnRow[0]);
+            }
```
Comment (antonyharfield) [inline role-guardian/src/main/java/org/rfcx/guardian/guardian/asset/detections/AudioDetectionJsonUtils.java:53]: This looks like it is changing the algorithm and could lead to the database filling up. Can we avoid this change and keep the algorithm the same?

**Review by antonyharfield — CHANGES_REQUESTED** [review]

**Review by antonyharfield — APPROVED** [review]
